<a href="https://colab.research.google.com/github/rakesh-mandal/ML/blob/main/day55-Ridge_Regression/Ridge2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import SGDRegressor

from sklearn.metrics import r2_score, mean_squared_error

In [ ]:
diabetes = load_diabetes()

In [ ]:
X=diabetes.data
y=diabetes.target

In [ ]:
X.shape , y.shape

((442, 10), (442,))

In [ ]:
df=pd.DataFrame(X)
df

,0,1,2,3,4,5,6,7,8,9
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [ ]:
print(df.mean())
print(df.std())

0   -1.444295e-18
1    2.543215e-18
2   -2.255925e-16
3   -4.854086e-17
4   -1.428596e-17
5    3.898811e-17
6   -6.028360e-18
7   -1.788100e-17
8    9.243486e-17
9    1.351770e-17
dtype: float64
0    0.047619
1    0.047619
2    0.047619
3    0.047619
4    0.047619
5    0.047619
6    0.047619
7    0.047619
8    0.047619
9    0.047619
dtype: float64

In [ ]:
print(np.allclose(df.describe().loc['mean'], df.mean()))

True

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

#1. Linear Regression (Normal Equation)

In [ ]:
lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Linear Regression")
print("R² =", r2_score(y_test, y_pred_lr))
print("RMSE =", np.sqrt(mean_squared_error(y_test, y_pred_lr)))

Linear Regression
R² = 0.4526027629719195
RMSE = 53.85344583676593

In [ ]:
print(lr.coef_)
print(lr.intercept_)

[  37.90402135 -241.96436231  542.42875852  347.70384391 -931.48884588
  518.06227698  163.41998299  275.31790158  736.1988589    48.67065743]
151.34560453985995

#2. Linear Regression (Gradient Descent)

In [ ]:
lr_gd = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SGDRegressor(
        loss='squared_error',
        penalty=None,
        learning_rate='constant',
        eta0=0.01,
        max_iter=5000,
        random_state=42
    ))
])

lr_gd.fit(X_train, y_train)

y_pred_lr_gd = lr_gd.predict(X_test)

print("Linear Regression (GD)")
print("R² =", r2_score(y_test, y_pred_lr_gd))
print("RMSE =", np.sqrt(mean_squared_error(y_test, y_pred_lr_gd)))

Linear Regression (GD)
R² = 0.428813451988975
RMSE = 55.01120802230918

In [ ]:
lr_gd.named_steps['model'].coef_

array([  4.80717805, -11.92795198,  26.3280931 ,  16.69389541,
       -17.44130729,   0.04366961,  -6.91189613,  10.03355583,
        25.41967097,   4.55228213])

In [ ]:
print(lr_gd.named_steps['model'].coef_)
print(lr_gd.named_steps['model'].intercept_)

[  4.80717805 -11.92795198  26.3280931   16.69389541 -17.44130729
   0.04366961  -6.91189613  10.03355583  25.41967097   4.55228213]
[154.87428626]

#3. Ridge Regression (Closed-form)

In [ ]:
ridge = Ridge(alpha=1)

ridge.fit(X_train, y_train)

y_pred_ridge = ridge.predict(X_test)

print("Ridge Regression")
print("R² =", r2_score(y_test, y_pred_ridge))
print("RMSE =", np.sqrt(mean_squared_error(y_test, y_pred_ridge)))

Ridge Regression
R² = 0.41915292635986545
RMSE = 55.47446204180109

In [ ]:
print(ridge.coef_)
print(ridge.intercept_)

[  45.36737726  -76.66608563  291.33883165  198.99581745   -0.53030959
  -28.57704987 -144.51190505  119.26006559  230.22160832  112.14983004]
152.241675211113

In [ ]:
class MeraRidge:

    def __init__(self,alpha=1):

        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):

        X_train = np.insert(X_train,0,1,axis=1)
        I = np.identity(X_train.shape[1])
        I[0][0] = 0
        result = np.linalg.inv(np.dot(X_train.T,X_train) + self.alpha * I).dot(X_train.T).dot(y_train)
        self.intercept_ = result[0]
        self.coef_ = result[1:]

    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [ ]:
reg = MeraRidge()
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
#print(y_pred)
print(r2_score(y_test,y_pred))
print(reg.coef_)
print(reg.intercept_)

0.41915292635986545
[  45.36737726  -76.66608563  291.33883165  198.99581745   -0.53030959
  -28.57704987 -144.51190505  119.26006559  230.22160832  112.14983004]
152.24167521111292

#4. Ridge Regression (Gradient Descent)

In [ ]:
ridge_gd = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SGDRegressor(
        loss='squared_error',
        penalty='l2',
        alpha=1.0,
        learning_rate='constant',
        eta0=0.01,
        max_iter=5000,
        random_state=42
    ))
])

ridge_gd.fit(X_train, y_train)

y_pred_ridge_gd = ridge_gd.predict(X_test)

print("Ridge Regression (GD)")
print("R² =", r2_score(y_test, y_pred_ridge_gd))
print("RMSE =", np.sqrt(mean_squared_error(y_test, y_pred_ridge_gd)))

Ridge Regression (GD)
R² = 0.4258204816169101
RMSE = 55.15514680683742

In [ ]:
print(ridge_gd.named_steps['model'].coef_)
print(ridge_gd.named_steps['model'].intercept_)

[-2.244626   -4.12789327 13.98473342 11.69537869 -1.81660077 -3.62995766
 -6.63010748  4.87414815 12.10995712  8.19229054]
[155.56515496]

In [ ]:
class MeraRidgeGD:

    def __init__(self,epochs,learning_rate,alpha):

        self.learning_rate = learning_rate
        self.epochs = epochs
        self.alpha = alpha
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):

        self.coef_ = np.ones(X_train.shape[1])
        self.intercept_ = 0
        thetha = np.insert(self.coef_,0,self.intercept_)

        X_train = np.insert(X_train,0,1,axis=1)

        for i in range(self.epochs):
            reg = self.alpha * thetha
            reg[0] = 0
            thetha_der = np.dot(X_train.T,X_train).dot(thetha) - np.dot(X_train.T,y_train) + reg
            thetha = thetha - self.learning_rate*thetha_der

        self.coef_ = thetha[1:]
        self.intercept_ = thetha[0]

    def predict(self,X_test):

        return np.dot(X_test,self.coef_) + self.intercept_

In [ ]:
reg = MeraRidgeGD(epochs=500,learning_rate=0.005,alpha=1)

In [ ]:
reg.fit(X_train,y_train)

y_pred = reg.predict(X_test)
print("R2 score",r2_score(y_test,y_pred))
print(reg.coef_)
print(reg.intercept_)

R2 score 0.4184315182860632
[  45.55938263  -74.93767259  289.32059884  198.16667335    0.56622937
  -27.82541862 -144.27848212  119.23307569  228.74337919  113.64422788]
152.2460145185549

#5. Results

In [ ]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Linear Regression (GD)",
        "Ridge Regression",
        "Ridge Regression (GD)"
    ],
    "R2 Score": [
        r2_score(y_test, y_pred_lr),
        r2_score(y_test, y_pred_lr_gd),
        r2_score(y_test, y_pred_ridge),
        r2_score(y_test, y_pred_ridge_gd)
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, y_pred_lr)),
        np.sqrt(mean_squared_error(y_test, y_pred_lr_gd)),
        np.sqrt(mean_squared_error(y_test, y_pred_ridge)),
        np.sqrt(mean_squared_error(y_test, y_pred_ridge_gd))
    ]
})

print(results)

                    Model  R2 Score       RMSE
0       Linear Regression  0.452603  53.853446
1  Linear Regression (GD)  0.428813  55.011208
2        Ridge Regression  0.419153  55.474462
3   Ridge Regression (GD)  0.425820  55.155147