<a href="https://colab.research.google.com/github/rakesh-mandal/ML/blob/main/day26-Ordinal_encoding/day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/customer.csv')
df.sample(5)

    age  gender   review education purchased
29   83  Female  Average        UG       Yes
21   32    Male  Average        PG        No
16   59    Male     Poor        UG       Yes
46   64  Female     Poor        PG        No
31   22  Female     Poor    School       Yes

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        50 non-null     int64
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [4]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [5]:
df.select_dtypes(include='number').columns

Index(['age'], dtype='object')

In [6]:
df.select_dtypes(include=['object', 'category']).columns

Index(['gender', 'review', 'education', 'purchased'], dtype='object')

In [7]:
df = df.iloc[:,2:]

In [8]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('purchased', axis=1),
                                                    df['purchased'],
                                                    test_size=0.2,
                                                    random_state=0)

X_train.shape, X_test.shape

((40, 2), (10, 2))

In [10]:
X_train

     review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [11]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [13]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [14]:
X_train = oe.transform(X_train)

In [ ]:
X_train

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [15]:
X_test = oe.transform(X_test)

In [16]:
X_test

array([[0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
y_test

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 0])

In [17]:
X_test

array([[0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.]])

In [20]:
X_train = pd.DataFrame(
    X_train,
    columns=['review', 'education']
)

In [21]:
X_train

    review  education
0      2.0        2.0
1      0.0        0.0
2      0.0        2.0
3      1.0        0.0
4      2.0        0.0
5      0.0        0.0
6      0.0        2.0
7      0.0        2.0
8      2.0        1.0
9      1.0        1.0
10     0.0        1.0
11     1.0        1.0
12     1.0        1.0
13     0.0        1.0
14     2.0        2.0
15     1.0        0.0
16     0.0        2.0
17     1.0        1.0
18     1.0        0.0
19     2.0        0.0
20     1.0        0.0
21     0.0        1.0
22     2.0        0.0
23     2.0        1.0
24     0.0        1.0
25     0.0        0.0
26     1.0        2.0
27     1.0        2.0
28     2.0        0.0
29     2.0        0.0
30     2.0        1.0
31     1.0        2.0
32     0.0        2.0
33     2.0        1.0
34     0.0        2.0
35     0.0        2.0
36     2.0        2.0
37     1.0        0.0
38     2.0        2.0
39     1.0        1.0